#!/bin/bash
#: Title	: report 
#: Date		: 2020-11-03
#: Author	: Hemantharaj M
#: Version	: 1.0
#: Descriptions : print formated sales report 
#: Options	: None

##Bulid a long string of equals signs
divider===================================
divider=$divider$divider

##Formated strings for printf
header="\n %-10s %11s %8s %10s\n"
format=" %-10s %11.2f %8d %10.2f\n"

##width of divider
totalwidth=44

##Print categories
printf "$header" ITEM "PER UNIT" NUM TOTAL

##Print divider to match width of format
printf "%$totalwidth.${totalwidth}s\n" "$divider"

##Print the line of report
printf "$format" \ Chair 79.95 4 319.8 \ Table 209.99 1 209.99 \ Armchair 315.49 2 630.98
